### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by MorleyB** [BinPar/read-conventional-commit-changelog#4]
Posting this warning here for visibility.

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Thank you for creating this action.

**Comment by Mgonand** [comment]
Thanks for letting me know about this issue. I appreciate you taking the time to point it out.
I will fix this as soon as I can but, in the meantime, if you have any suggested fixes, feel free to open a pull request and I will review it.
