### ISSUE TITLE
Nodejs 12 deprecated

### ISSUE THREAD

**Issue by gpongelli** [BinPar/read-conventional-commit-changelog#5]
Hi,
thanks for this action, I've started using it today and it does its job in excellent way!

After my [first release](https://github.com/gpongelli/broadlink-listener/actions/runs/3659658173) execution with this action, GitHub tells the following deprecation:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: BinPar/read-conventional-commit-changelog@v2.0.0
```

Waiting for your next release!

Thanks.

**Comment by Mgonand** [comment]
Thank for reaching out. I'm releasing a little update to fix the warning.

**Comment by gpongelli** [comment]
> Thank for reaching out. I'm releasing a little update to fix the warning.

I saw the MR, thank you for this action 🔝
